### ISSUE TITLE
Hmember Structural Profile

### ISSUE THREAD

**Issue by PeterAUNZ** [scottmitchell/HowickMaker-for-Dynamo#3]
Hi Scott,

I am having an issue , perhaps due to the use of a metric version of dynamo/revit.

When extruding the profile it comes out a scale much smaller that what would be expected. 

Have you experienced this before/ do you believe their is a work around?

![error 1](https://user-images.githubusercontent.com/57202459/67910542-fb153900-fbe7-11e9-9fe2-b5ed322acc69.JPG)
![error 2](https://user-images.githubusercontent.com/57202459/67910609-416a9800-fbe8-11e9-8437-261fe7ed312a.JPG)
![error 3](https://user-images.githubusercontent.com/57202459/67910614-43ccf200-fbe8-11e9-9285-dc5be75b6e04.JPG)

**Comment by PeterAUNZ** [comment]
Just to add the members then are too big when using imperial!

![error 4](https://user-images.githubusercontent.com/57202459/67910798-0321a880-fbe9-11e9-8754-1e6a54eced8a.JPG)

**Comment by scottmitchell** [comment]
@PeterAUNZ your units could definitely be part of the problem. HowickMaker currently only supports working in inches, although if you are building the repo yourself, it should be pretty easy to change that. Can you tell me a bit more about what you are trying to do?

**Comment by PeterAUNZ** [comment]
Im trying to take lines and create H.members from them. 

I can get it to drawing the members but the profile is far too small and I'm worried this will have an effect on the operations. How would I go about changing the reference units in the script (Sorry for my naivety I'm not a coder!)

**Comment by scottmitchell** [comment]
No worries! In that case, it will be a lot easier to just scale your lines right before you bring them into the HowickMaker node, rather than mess with the code. For example, if you’re working in feet, scale x12. If you’re working in meters, scale x39.37. Keep in mind this will ultimately give you a csv in inches.

**Comment by PeterAUNZ** [comment]
Great thanks Scott, really appreciate you helping out! Im really excited about what can be done working with Howick machines. Obviously your work and Nathan Peters have been a great exploration into the possibilities!

**Comment by scottmitchell** [comment]
No problem—happy to help anytime. There’s a ton of super cool stuff you can do with this machine, especially when combined with parametric workflows. I’d love to hear about what you end up doing with it.
