### ISSUE TITLE
Would it work with frama 5600???

### ISSUE THREAD

**Issue by Darozas** [scottmitchell/HowickMaker-for-Dynamo#4]
Hi 

Would it work with frama 5600???

Regards

**Comment by scottmitchell** [comment]
Hi,

Yes, it's possible to use it with the 5600, but you would have to make some adjustments to this repo to account for the stud dimension on the 5600. [This](https://github.com/scottmitchell/HowickMaker-for-Dynamo/blob/master/HowickMaker/hStructure.cs#L22-L23) would be the place to start.

**Comment by Darozas** [comment]
Hi 
Thanks for your time.

Can you please advise me how to change units? I want to make it all in metric.Is there a way to set it so it takes from revit ??

Regards

**Comment by scottmitchell** [comment]
It currently only supports inches. If you want to change units, you'll need to adjust a number of values in the source code. Again, this would be a good place to start: https://github.com/scottmitchell/HowickMaker-for-Dynamo/blob/master/HowickMaker/hStructure.cs#L22-L23

**Comment by Darozas** [comment]
Hi Thanks for your time again.

Can you please send me simple snipshot of what to change that will help me get going.
Im fearly new to csharp but keen to learn

Regards

**Comment by Darozas** [comment]
Do i heading wright way ???

Regards

`        [IsVisibleInDynamoLibrary(true)]
        [MultiReturn(new[] { "member", "operations" })]
        public static Dictionary<string, object> DrawAsMesh(Member member)
        {
            var DSWebAxis = HMDynamoUtil.HMLineToDSLine(member.WebAxis);
            var DSWebNormal = HMDynamoUtil.TripleToVector(member.WebNormal);

            Geo.Point OP1 = DSWebAxis.StartPoint;
            Geo.Point OP2 = DSWebAxis.EndPoint;

            Geo.Vector webAxis = Geo.Vector.ByTwoPoints(OP1, OP2);
            Geo.Vector normal = DSWebNormal;
            Geo.Vector lateral = webAxis.Cross(normal);
            lateral = lateral.Normalized();
            lateral = lateral.Scale(_StudWidth / 2);
            normal = normal.Normalized();
            normal = normal.Scale(_StudHeight);
            Geo.Vector lateralR = Geo.Vector.ByCoordinates(lateral.X * -1, lateral.Y * -1, lateral.Z * -1);

            Geo.Point p0 = OP1.Add(normal.Add(lateral));
            Geo.Point p1 = OP2.Add(normal.Add(lateral));
            Geo.Point p2 = OP1.Add(lateral);
            Geo.Point p3 = OP2.Add(lateral);
            Geo.Point p6 = OP1.Add(normal.Add(lateralR));
            Geo.Point p7 = OP2.Add(normal.Add(lateralR));
            Geo.Point p4 = OP1.Add(lateralR);
            Geo.Point p5 = OP2.Add(lateralR);

            Geo.Point[] pts = { p0, p1, p2, p1, p2, p3, p2, p3, p4, p3, p4, p5, p4, p5, p6, p5, p6, p7 };

            Geo.IndexGroup g0 = Geo.IndexGroup.ByIndices(0, 1, 2);
            Geo.IndexGroup g1 = Geo.IndexGroup.ByIndices(3, 4, 5);
            Geo.IndexGroup g2 = Geo.IndexGroup.ByIndices(6, 7, 8);
            Geo.IndexGroup g3 = Geo.IndexGroup.ByIndices(9, 10, 11);
            Geo.IndexGroup g4 = Geo.IndexGroup.ByIndices(12, 13, 14);
            Geo.IndexGroup g5 = Geo.IndexGroup.ByIndices(15, 16, 17);

            Geo.IndexGroup[] ig = { g0, g1, g2, g3, g4, g5 };

            Geo.Mesh mesh = Geo.Mesh.ByPointsFaceIndices(pts, ig);

            var points = new List<Geo.Point>();

            foreach (HM.hOperation op in member.Operations)
            {
                points.Add(HMDynamoUtil.TripleToPoint(member.WebAxis.PointAtParameter(op._loc / member.WebAxis.Length)));
            }

            return new Dictionary<string, object>
            {
                { "member", mesh },
                { "operations", points }
            };

        }`

**Comment by Darozas** [comment]
Thanks got it going well now.

`internal double _StudHeight = 50;
        internal double _StudWdith = 75;
        internal double _Studlip = 10;
        internal double _Studthc = 1.6;
        internal double _LipPunchWidth = 46;
        internal double _WebPunchWidth = 48;`


`                   case Operation.LIP_CUT:
                    lateral = lateral.Normalized().Scale(_StudWdith/2);
                    lateralR = lateralR.Normalized().Scale(_StudWdith/2);
                    webAxis = webAxis.Normalized().Scale(_LipPunchWidth /2);
                    webAxisR = webAxisR.Normalized().Scale(_LipPunchWidth /2);
                    normal = normal.Normalized().Scale(_StudHeight+0.1);
                    normalR = normalR.Normalized().Scale(_Studthc);
                    Geo.Vector lateral2 = lateral.Normalized().Scale(_Studlip*2);
                    Geo.Vector lateral2R = lateralR.Normalized().Scale(_Studlip*2);`
