### ISSUE TITLE
Wont compile Name space missing 

### ISSUE THREAD

**Issue by Darozas** [scottmitchell/HowickMaker-for-Dynamo#5]
Hi 

Trying to compile code but getting error 

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Could not resolve this reference. Could not locate the assembly "MeshToolkit". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	HowickMakerDynamo	

Can you please advise me here 

Regards

**Comment by scottmitchell** [comment]
You need to download MeshToolkit from the Dynamo Package Mananger (or from https://dynamopackages.com/) and reference the MeshToolkit dll.

**Comment by Darozas** [comment]
Thanks 

Worked like a dream.

I see latest code doesn't match readme file. Do you have any plans for updating it ??

Regards

**Comment by Darozas** [comment]
There non dynamo nodes coming in ??

I having trouble of nothing is being displayed in background when using "Triple" node and Line node.

Can you please advise here??

Regards

![notworking](https://user-images.githubusercontent.com/19796221/73309942-2aedd000-421b-11ea-9daa-eefdc63f08d7.png)

**Comment by scottmitchell** [comment]
Glad that worked. Unfortunately, I don't currently have time to make any improvements to this repo myself. But if you want to make a PR, I'm more than happy to review it for you.

**Comment by scottmitchell** [comment]
Many of those classes, including Triple and Line, are internal HowickMaker classes. Not sure why they are appearing in Dynamo.

**Comment by Darozas** [comment]
Thanks for your time again.

I just compiled code by clicking on "HowickMakerDynamo" and getting loads of new nodes but there is no old nodes from previous build.
And cant get it to work.older builds works fine

![Untitled](https://user-images.githubusercontent.com/19796221/73311204-ce3fe480-421d-11ea-84e8-86a0f104e980.png)

**Comment by Darozas** [comment]
Hi
